# Generated by Django 5.0.7 on 2024-07-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.CharField(default='sample.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(default='sample.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='active',
            field=models.CharField(default='Activated', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='active',
            field=models.CharField(default='Activated', max_length=100),
        ),
    ]
