# Generated by Django 5.0.7 on 2024-07-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_candidate_image_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.CharField(default='https://firebasestorage.googleapis.com/v0/b/careerconnect-5ad6c.appspot.com/o/candidates%2Fsample.png?alt=media', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(default='https://firebasestorage.googleapis.com/v0/b/careerconnect-5ad6c.appspot.com/o/companies%2Fsample.png?alt=media', max_length=255),
        ),
    ]
