# Generated by Django 5.0.7 on 2024-07-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_candidate_image_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
