# Generated by Django 5.0.7 on 2024-08-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_candidate_resume_candidate_resumes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='active',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='active',
            new_name='status',
        ),
    ]
