# Generated by Django 5.0.7 on 2024-07-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='candidateId',
            new_name='candidate_id',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='jobId',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='companyId',
            new_name='company_id',
        ),
    ]
