# Generated by Django 5.0.7 on 2024-07-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_candidateid_application_candidate_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='candidate_id',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company_id',
            new_name='company',
        ),
    ]
