# Generated by Django 5.0.7 on 2024-07-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_rename_candidate_id_application_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.TextField(),
        ),
    ]
