# Generated by Django 5.0.7 on 2024-07-25 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
