# Generated by Django 5.0.7 on 2024-07-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(default='Thương lượng', max_length=255),
        ),
    ]
